### ISSUE TITLE
telegraf.service - The plugin-driven server agent for reporting metric into I

### ISSUE THREAD

**Issue by ChieF-TroN** [x70b1/telegraf-edgeos#2]
I have an ER8-Pro on firmware v2.0.9-hotfix.2

I followed your installation instructions, however the service is failing:
![image](https://user-images.githubusercontent.com/27984100/173483272-48aceb15-db51-4313-9fad-696fbdcd7e6f.png)

I do see that telegraf is in /usr/bin, and all I did was input my influxdb url, username, and password into the telegraf.conf.

**Comment by x70b1** [comment]
Whats your package version?

Check your logs with `journalctl -u telegraf -f`.

**Comment by x70b1** [comment]
I have found an issue. It is fixed in the latest [release](https://github.com/x70b1/telegraf-edgeos/releases/tag/v1.23.0-2). Please try that version.

**Comment by ChieF-TroN** [comment]
Unfortunately this did not resolve this issue.
![image](https://user-images.githubusercontent.com/27984100/173733544-600ed134-9035-4668-823c-db3f075d307d.png)

Here is my config, it's just the sample config with my influxdb credentials/server plugged in.
![image](https://user-images.githubusercontent.com/27984100/173733799-eb378bd2-cada-4e86-970f-6c25ea6ca817.png)

I forgot to mention I'm using the mips package.

Edit: I realize that the above conf screenshot shows everything being commented out. I realized this later and removed the comments, but still the same results.

**Comment by ChieF-TroN** [comment]
I resolved this issue. I had both the [[inputs.exec]] uncommented resulting in this error. commenting out the second inputs.exec and the latter resolved this issue. I apologize, I'm a very new to how telegraf works.

**Comment by x70b1** [comment]
The second inputs.exec section should also work. It seems like a config error.
You can play with this command:

```
/usr/bin/telegraf --test --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --debug
```

You find the info about the commands [here](https://docs.influxdata.com/telegraf/v1.21/administration/commands/).
